### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by almarklein** [almarklein/faq-div#3]
* [x] ~Make those three lines to add to your page select-able. Feels more tangible.~
* [x] Short summaries to explain each example.
* [x] Improve the design.
* [x] Improve the design more (get help?).
* [x] Ad on Pyzo.org?
* [x] Go OSS?
* [x] WordPress plugin or docs.
* [x] Blog posts for more organic traffic?
